version: "3.9"

services:
  registry:
    image: registry:3
    container_name: registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - /home/kovo/docker/volumes/registry:/var/lib/registry
      - /home/kovo/docker/dockerfiles/registry-config/config.yml:/etc/distribution/config.yml
      - /home/kovo/docker/auth:/auth

  registry-ui:
    image: joxit/docker-registry-ui:main
    container_name: registry-ui
    restart: unless-stopped
    depends_on:
      - registry
    ports:
      - "9080:80"
    environment:
      REGISTRY_TITLE: Private Docker Registry
      NGINX_PROXY_PASS_URL: http://registry:5000
      NGINX_RESOLVER: 127.0.0.11
      SINGLE_REGISTRY: "true"
      REGISTRY_SECURED: "true"
      DELETE_IMAGES: "true"
