version: '3.8'

services:

  paster-cloud-db:
    image: postgres:16.2-alpine
    container_name: paster-cloud-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-paster}
      POSTGRES_PASSWORD: ${DB_USER_PASSWORD}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "5432:5432"
    volumes:
      - ${DB_VOLUME:-/home/kovo/docker/volumes/paster-cloud/postgres}:/var/lib/postgresql/data
    networks:
      - paster-cloud-private

  paster-cloud-backend:
    image: k0v0/kovo-docker-repo:paster-cloud-backend-2024-03-25
    container_name: paster-cloud-backend
    restart: always
    environment:
      SECRET_KEY: ${SECRET_KEY}
      SPRING_DATASOURCE_USER: ${DB_USER}
      SPRING_DATASOURCE_PASS: ${DB_USER_PASSWORD}
      SPRING_DATASOURCE_URL: ${DB_URL:-jdbc:postgresql://paster-cloud-db:5432/paster}
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      VIRTUAL_HOST: ${VIRTUAL_HOST:-api.paster.cloud}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-4004}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-api.paster.cloud}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-kovo.mato@gmail.com}
    ports:
      - "4004:4004"
    volumes:
      - ${FILE_UPLOADS_DIR:-/home/kovo/docker/volumes/paster-cloud/upload}:/app/uploads/files
      - ${FILE_TEMP_DIR:-/home/kovo/docker/volumes/paster-cloud/temp}:/app/uploads/temp
    networks:
      - nginx-proxy
      - paster-cloud-private
    #depends_on:
      #paster-cloud-db:
        #condition: service_healthy

  paster-cloud-frontend:
    image: k0v0/kovo-docker-repo:paster-cloud-frontend-2024-04-29
    container_name: paster-cloud-frontend
    restart: always
    environment:
      API_KEY: ${API_KEY}
      API_VERSION: ${API_VERSION:-1}
      BACKEND_API: ${BACKEND_API:-https://api.paster.cloud}
      BACKEND_WEBSOCKET: ${BACKEND_WEBSOCKET:-wss://api.paster.cloud/websocket}
      VIRTUAL_HOST: ${VIRTUAL_HOST:-paster.cloud}
      VIRTUAL_PORT: ${VIRTUAL_PORT:-4204}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST:-paster.cloud}
      LETSENCRYPT_EMAIL: ${LETSENCRYPT_EMAIL:-kovo.mato@gmail.com}
    ports:
      - "4204:80"
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
  paster-cloud-private:
    external: true
