name: Registry garbage collection

on:
  workflow_dispatch:

permissions: {}

jobs:
  garbage-collect:
    runs-on: ubuntu-latest
    steps:
      - name: Run garbage collection over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_SSH_KEY }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            export DOCKER_HOST=unix:///run/user/1000/docker.sock
            docker exec registry /bin/registry garbage-collect --delete-untagged /etc/distribution/config.yml